apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: eglpl6egj-python 
  janus-idp.io/tekton: eglpl6egj-python
  backstage.io/kubernetes-id: eglpl6egj-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: eglpl6egj-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml