apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: eglpl6egj-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: eglpl6egj-python 
  name: eglpl6egj-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: eglpl6egj-python 
